controllers/AsuntosController.php
<?php

namespace app\controllers;

use app\models\Asuntos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AsuntosController implements the CRUD actions for Asuntos model.
 */
class AsuntosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Asuntos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Asuntos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Asuntos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Asuntos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Asuntos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Asuntos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Asuntos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Asuntos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Asuntos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Asuntos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/CamasController.php
<?php

namespace app\controllers;

use app\models\Camas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CamasController implements the CRUD actions for Camas model.
 */
class CamasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Camas models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Camas::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Camas model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Camas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Camas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Camas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Camas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Camas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Camas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Camas::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/HorasController.php
<?php

namespace app\controllers;

use app\models\Horas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HorasController implements the CRUD actions for Horas model.
 */
class HorasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Horas models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Horas::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Horas model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Horas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Horas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Horas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Horas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Horas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Horas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Horas::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Pacientes;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
        public function actionMostrarpacientes(){
        $dataProvider = new ActiveDataProvider([
        'query' => Pacientes::find(),
        'pagination' => [
            'pageSize' => 10, // Ajusta según sea necesario
        ],
    ]);

    return $this->render('pacientes2', [
        'dataProvider' => $dataProvider,
    ]);
    }
    
    public function actionRegistros()
    {
    return $this->render('registros'); // Este es el nombre de tu vista en el archivo 'registros.php'
    }
    
    
    public function actionVerprotocolos() {
    // Ruta al archivo PDF
    $pdfPath = Yii::getAlias('@webroot') . '/documentos/rcp.pdf';

    // Verificar si el archivo existe
    if (file_exists($pdfPath)) {
        // Devolver el contenido del PDF al navegador
        return Yii::$app->response->sendFile($pdfPath, 'rcp.pdf', ['inline' => true]);
    } else {
        // Manejar el caso en que el archivo no existe
        throw new \yii\web\NotFoundHttpException('El archivo PDF no se encuentra.');
    }
}

  public function actionProtocolos()
    {
    return $this->render('protocolos'); // Este es el nombre de tu vista en el archivo 'registros.php'
    }
    
}

views/site/_pacientes2.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;

// $model representa un modelo de ciclista que será proporcionado por el ListView
?>


<!--Este es el código que determina cómo se muestran los datos y qué maquetación tienen en el ListView-->
<div class="media">
    <div class="media-body">
        <h4 class="media-heading"><?='Nombre completo: ' . Html::encode($model->nombreCompleto) ?></h4>
        <p><?= 'Id: ' . Html::encode($model->id) ?></p>
        <p><?= 'Número de historia: ' . Html::encode($model->numeroHistoria) ?></p>
        <p><?= 'Fecha de nacimiento: ' . Html::encode($model->fechaNacimiento) ?></p>
    </div>
</div>

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\bootstrap\BootstrapAsset;
use yii\helpers\Url;

$this->title = 'My Yii Application';
?>
<div class="site-index">      
    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">GANDARA</h1>

        <p class="lead">Cuidado de los pacientes.</p>

        <div class="btn-group" role="group">
        <a class="btn btn-lg btn-success mr-3" href="<?= Yii::$app->urlManager->createUrl(['/site/registros']) ?>">Registros</a>
        <a class="btn btn-lg btn-success" href="<?= Yii::$app->urlManager->createUrl(['/site/protocolos']) ?>">Protocolos</a>

    </div>
    </div>

       
<div class="body-content">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card alturaminima tarjeta-separada">
                <div class="card-body tarjeta">
                    <h3>Menstruaciones</h3>
                    <p>Acceso al registro de mentruaciones de los pacientes de la unidad.</p>
                    <p>
                        <?= Html::a('Menstruaciones', ['menstruaciones/index'], ['class' => 'btn btn-primary'])?>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="card alturaminima tarjeta-separada">
                <div class="card-body tarjeta">
                    <h3>Revisiones</h3>
                    <p>Acceso al registro de revisiones de los pacientes de la unidad.</p>
                    <p>
                        <?= Html::a('Revisiones', ['revisiones/index'], ['class' => 'btn btn-primary'])?>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="card alturaminima tarjeta-separada">
                <div class="card-body tarjeta">
                    <h3>Deposiciones</h3>
                    <p>Acceso al registro de deposiciones de los pacientes de la unidad.</p>
                    <p>
                        <?= Html::a('Deposiciones', ['deposiciones/index'], ['class' => 'btn btn-primary'])?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>


    
    
    
        </div>

            <div class="card-deck text-center mt-2">
            <div class="card mx-2">
                <a href="<?= Url::to('site/mostrarpacientes') ?>" class="card-body btn btn" data-title="Censo">
                    <img src="<?= Yii::getAlias('@web') ?>/images/censo.png" alt="Censo">
                </a>
            </div>
            <div class="card mx-2">
                <a href="<?= Url::to(['site/mostrarpacientes']) ?>" class="card-body btn btn-sm" data-title="Mapa de camas">
                    <img src="<?= Yii::getAlias('@web') ?>/images/mapa.png" alt="Censo">
                </a>
            </div>
            <div class="card mx-2">
                <a href="<?= Url::to(['site/mostrarpacientes']) ?>" class="card-body btn btn-sm" data-title="Alertas">
                    <img src="<?= Yii::getAlias('@web') ?>/images/alerta.png" alt="Censo">
                </a>
            </div>
        </div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/pacientes2.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\bootstrap\BootstrapAsset;


// Definición del título
$this->title = 'Censo de los pacientes';

?>


<!--Este el el código del widget del ListView-->
<div class="mt-5"> <!-- Agregamos un margen superior de 3 unidades de espacio -->
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_pacientes2',
        'layout' => "{items}\n{pager}",
        'options' => ['class' => 'list-view'], // Clase de Bootstrap
        'itemOptions' => ['class' => 'media'], // Clase de Bootstrap para cada elemento
    ]); ?>
</div>

views/site/protocolos.php
<?php

use yii\helpers\Html;

$this->title = 'Protocolos';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-protocolos">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-12">
            <?php
            echo Html::a('Protocolo de RCP', ['/site/verprotocolos'], ['class' => 'btn btn-primary', 'target' => '_blank']);
            ?>
        </div>
    </div>
</div>

views/site/registros.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Registros';
$this->params['breadcrumbs'][] = $this->title;
?>

<style>
    .tarjeta {
        margin: 10px; /* Margen entre las tarjetas */
    }
</style>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Asuntos</h3>
                <p>Registro de asuntos.</p>
                <p>
                    <?= Html::a('Asuntos', ['/asuntos/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Atenciones</h3>
                <p>Registro de atenciones.</p>
                <p>
                    <?= Html::a('Atenciones', ['/atenciones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Auxiliares</h3>
                <p>Registro de auxiliares.</p>
                <p>
                    <?= Html::a('Auxiliares', ['/auxiliares/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Camas</h3>
                <p>Registro de camas.</p>
                <p>
                    <?= Html::a('Camas', ['/camas/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Deposiciones</h3>
                <p>Registro de deposiciones.</p>
                <p>
                    <?= Html::a('Deposiciones', ['/deposiciones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Habitaciones</h3>
                <p>Registro de habitaciones.</p>
                <p>
                    <?= Html::a('Habitaciones', ['/habitaciones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Horas</h3>
                <p>Registro de horas.</p>
                <p>
                    <?= Html::a('Horas', ['/horas/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Menstruaciones</h3>
                <p>Registro de menstruaciones.</p>
                <p>
                    <?= Html::a('Menstruaciones', ['/menstruaciones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Pacientes</h3>
                <p>Registro de pacientes.</p>
                <p>
                    <?= Html::a('Pacientes', ['/pacientes/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Revisiones</h3>
                <p>Registro de revisiones.</p>
                <p>
                    <?= Html::a('Revisiones', ['/revisiones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Deposiciones</h3>
                <p>Registro de deposiciones.</p>
                <p>
                    <?= Html::a('Deposiciones', ['/deposiciones/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4">
        <div class="card alturaminima tarjeta-separada">
            <div class="card-body tarjeta">
                <h3>Teléfonos</h3>
                <p>Registro de Teléfonos.</p>
                <p>
                    <?= Html::a('Teléfonos', ['/telefonos/index'], ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
        </div>
    </div> 
    <!-- Repite el mismo patrón para los otros modelos -->
</div> 